version: '2'
services:
  
  mysql:
    command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_DATABASE=customerdata
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes